version: "1"
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/cochan/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    # Ensure the read and write access
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php7.1
      - php7.3
      - php7.4
      - php8.1
    networks:
      frontend:
        aliases:
          - php7.1 # 别名，实现内部互相访问
          - php7.3
          - php7.4
          - php8.1
    environment:
      TZ: Asia/Shanghai
  php7.1:
    build: ./php/php7.1-fpm-alpine/
    container_name: php7.1
    restart: always
    expose:
      - "9071:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/:rw
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
  php7.3:
    build: ./php/php7.3-fpm-alpine/
    container_name: php7.3
    restart: always
    expose: 
      - "9073:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/:rw
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
  php7.4:
    build: ./php/php7.4-fpm-alpine/
    container_name: php7.4
    restart: always
    expose:
      - "9074:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/:rw
    environment:
      TZ: Asia/Shanghai
    networks:
      - frontend
  php8.1:
    build: ./php/php8.1-fpm-alpine/
    container_name: php8.1
    restart: always
    expose: 
      - "9081:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/:rw
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/cochan/mysql:8.0
    restart: always
    container_name: mysql8.0
    ports:
      - "33068:3306"
    volumes:
      - ./data/mysql8.0:/var/lib/mysql
      - ./conf/mysql8.0:/etc/mysql/conf.d
      - ./logs/mysql8.0/:/logs
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/cochan/redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
networks:
  frontend:
    driver: bridge