version: "3"
services:
  nginx:
    image: registry.cn-guangzhou.aliyuncs.com/softstao/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    # Ensure the read and write access
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/  # 可根据自己项目文件夹修改
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx/
    links:
#      - php7.1
      - php7.2
#      - php7.4
      - php8.0
      - php8.1
      - mysql
      - redis
    networks:
      frontend:
        aliases:
#          - php7.1-fpm # 别名，实现内部互相访问
          - php7.2-fpm
#          - php7.3-fpm
#          - php7.4-fpm
          - php8.0-fpm
          - php8.1-fpm
          - mysql8.0
          - redis7.0
    environment:
      TZ: Asia/Shanghai
#  php7.1:
#    build: ./php/php7.1-fpm-alpine/
#    container_name: php7.1-fpm
#    restart: always
#    expose:
#      - "9000"
#    ports:
#      - "9071:9000"
#    privileged: true
#    volumes:
#      - ./workspace/:/data/workspace/
#    networks:
#      - frontend
#    environment:
#      TZ: Asia/Shanghai
  php7.2:
    build: ./php/php7.2-fpm/
    container_name: php7.2-fpm
    restart: always
    expose:
      - "9000"
    ports:
      - "9072:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
#  php7.3:
#    build: ./php/php7.3-fpm-alpine/
#    container_name: php7.3-fpm
#    restart: always
#    expose:
#      - "9000"
#    ports:
#      - "9073:9000"
#    privileged: true
#    volumes:
#      - ./workspace/:/data/workspace/
#    networks:
#      - frontend
#    environment:
#      TZ: Asia/Shanghai
#  php7.4:
#    build: ./php/php7.4-fpm-alpine/
#    container_name: php7.4-fpm
#    restart: always
#    expose:
#      - "9000"
#    ports:
#      - "9074:9000"
#    privileged: true
#    volumes:
#      - ./workspace/:/data/workspace/
#    environment:
#      TZ: Asia/Shanghai
#    networks:
#      - frontend
  php8.0:
    build: ./php/php8.0-fpm/
    container_name: php8.0-fpm
    restart: always
    expose:
      - "9000"
    ports:
      - "9080:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
  php8.1:
    build: ./php/php8.1-fpm/
    container_name: php8.1-fpm
    restart: always
    expose: 
      - "9000"
    ports:
      - "9081:9000"
    privileged: true
    volumes:
      - ./workspace/:/data/workspace/
    networks:
      - frontend
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/softstao/mysql:8.0
    restart: always
    container_name: mysql8.0
    ports:
      - "33068:3306"
    volumes:
      - ./data/mysql8.0:/var/lib/mysql
      - ./conf/mysql8.0:/etc/mysql/conf.d
      - ./logs/mysql8.0/:/logs
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
  redis:
    image: registry.cn-guangzhou.aliyuncs.com/softstao/redis:7.0
    container_name: redis7.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
networks:
  frontend:
    driver: bridge