FROM registry.cn-guangzhou.aliyuncs.com/softstao/php:8.2-fpm
LABEL author="COCHAN <cochan717@foxmail.com>"

# 安装基础包
# RUN set -x \
#     && apt-get update \
#     && composer self-update \
#     && apt-get install -y cron