FROM registry.cn-guangzhou.aliyuncs.com/softstao/php:7.2-fpm
LABEL author="COCHAN <cochan717@foxmail.com>"

# 安装基础包
#RUN apt update \
#    && composer self-update \
#    && apt-get install -y cron

# 安装相关扩展
#RUN set -x \
    # && docker-php-ext-configure gd --with-webp=/usr/include/webp --with-jpeg=/usr/include --with-freetype=/usr/include/freetype2/ \
    # && docker-php-ext-install -j$(nproc) gd \
    # && docker-php-ext-install pdo \
    # && docker-php-ext-install pdo_mysql \
    # && docker-php-ext-install mysqli \
#    && docker-php-ext-install bcmath